#plantilla insert actores
#INSERT INTO ACTORES (NOMBRE_APE,NACIONALIDAD,FECHA_NAC,DESCRIPCION,CARRERA,IMAGEN) VALUES ("","","","","","");

INSERT INTO ACTORES (NOMBRE_APE,NACIONALIDAD,FECHA_NAC,DESCRIPCION,CARRERA,IMAGEN) VALUES ("Christian Bale","Reino Unido","1973-01-30","Christian Bale (Haverfordwest, Gales, 30 de enero de 1974) actor de cine y televisión británico. Ganador de los premios Óscar y Globo de Oro","Christian Bale (Haverfordwest, Gales, 30 de enero de 1974) actor de cine y televisión británico. Ganador de los premios Óscar y Globo de Oro. Nació en la pequeña ciudad de Haverfordwest (13 000 habitantes), capital del condado de Pembrokeshire (Gales). Su padre era el activista sudafricano David Bale (1941-2003) y su madre, la británica Jenny James, trabajó en el circo como bailarina. Bale tuvo tres hermanas mayores. En el año 2000, rueda las películas Shaft: The Return y American Psycho. Cuatro años después, su papel en El maquinista, una producción española, le puso a prueba física y mentalmente a la hora de enfrentarse a uno de los roles más difíciles de su carrera hasta el momento. Su gran oportunidad llegó con Batman Begins (2005). En 2006 participó la película The Prestige junto a Hugh Jackman y Michael Caine, dirigida por Christopher Nolan. En el año 2007 participa en Rescue Dawn, I'm Not There y 3:10 to Yuma y en 2008 vuelve al papel de Batman en The Dark Knight, de la cual se han tenido muy buenas impresiones y ha roto récord de taquilla en Estados Unidos, al lograr más de 500 millones de dólares. Sus más recientes trabajos han sido en las cintas Terminator Salvation, donde interpretó a John Connor y Enemigos públicos, como Melvin Purvis, el Agente del FBI, al que J. Edgar Hoover encargó la cacería del famoso asaltante John Dillinger, interpretado por Johnny Depp. En el 2010, su carrera llegó a la cúspide cuando ganó el Óscar, el Globo de Oro y el Premio del Sindicato de Actores al Mejor Actor de Reparto por su interpretación de Dicky Eklund en la película The Fighter, interpretación que fue totalmente aclamada tanto por el público como por la crítica especializada. En 2012 interpreta por tercera y última vez a Batman / Bruce Wayne en The Dark Knight Rises, sellando así el final de la trilogía de Christopher Nolan del justiciero oscuro.","Christian_Bale.jpg");
INSERT INTO ACTORES (NOMBRE_APE,NACIONALIDAD,FECHA_NAC,DESCRIPCION,CARRERA,IMAGEN) VALUES ("Anne Hathaway","EEUU","1982-11-12","Anne Hathaway,(Brooklyn, Nueva York, Estados Unidos, 12 de noviembre de 1982), es una actriz de cine estadounidense.","Anne Hathaway, (Brooklyn, Nueva York, Estados Unidos, 12 de noviembre de 1982), es una actriz de cine estadounidense. Fue elegida como Mia Thermopolis en la película de comedia familiar de Disney The Princess Diaries (2001), con la que su carrera cobró impulso. Durante los siguientes tres años, Hathaway continuó protagonizando películas familiares, retomando el papel de Mia Thermopolis en la secuela, y como personaje principal en Ella Enchanted (ambas de 2004). Interesada en otros proyectos, Hathaway comenzó una transición de carrera con papeles de reparto en Caos y Brokeback Mountain (ambas de 2005). Posteriormente, fue coprotagonista junto a Meryl Streep en The Devil Wears Prada (2006) y apareció en Becoming Jane (2007) como la escritora Jane Austen. En 2008, obtuvo varios reconocimientos por su papel protagonista en la película La boda de Rachel, siendo nominada para el Premio Óscar a la mejor actriz. En 2009 protagonizó al lado de Kate Hudson la película Guerra de Novias. En 2010, protagonizó los éxitos de taquilla Valentine's Day y Alicia en el país de las maravillas. En 2012 interpretó a (Gatúbela (Catwoman) - Selina Kyle) la famosa rival y posteriormente aliada de (Bruce Wayne - Batman) Christian Bale en The Dark Knight Rises la cual fue la tercera y última entrega de la trilogía de Batman. En 2012 protagonizó la película musical 'Los Miserables' interpretando a Fantine, actuando junto a Hugh Jackman y Russell Crowe entre otros, recibiendo el Globo de Oro y el Óscar a la mejor actriz de reparto. Su estilo de actuación ha sido comparado con Judy Garland y Audrey Hepburn.1 Hathaway cita a Hepburn como una de sus actrices favoritas2 y a Streep como un icono.3 La revista People la nombró como una de las grandes estrellas descubiertas en 20014 y apareció por primera vez en la lista de las 50 personas más bellas del mundo de dicha revista en 2006.5 En 2011 dirigió la 83ª edición de los Premios Óscar, junto a James Franco.","Anne_Hathaway.jpg");
INSERT INTO ACTORES (NOMBRE_APE,NACIONALIDAD,FECHA_NAC,DESCRIPCION,CARRERA,IMAGEN) VALUES ("Tom Hardy","Reino Unido","1977-09-17","Tom Hardy (Londres, 15 de septiembre de 1977) es un actor de cine y de teatro británico. Conocido sobre todo por Bronson (2009).","Tom Hardy (Londres, 15 de septiembre de 1977) es un actor de cine y de teatro británico. Es conocido sobre todo por la película Bronson (2009) en la que interpreta el papel de protagonista que da nombre a la cinta, además de sus papeles secundarios en películas como Star Trek Nemesis, Origen (Inception) y El caballero oscuro de la saga de Batman. En 2010 recibió el BAFTA a la estrella emergente. Hardy nació en Walthernnol's y allí vivió hasta la edad de 20 años, luego se fue a Hammersmith y creció en el East Sheen de Londres. Su madre, Anni, era una artista y pintora de ascendencia católica irlandesa y su padre, Edward Chips Hardy, era escritor de comedias. Hardy estudió interpretación en el Reeds School, Tower House School, Richmond Drama School,y finalmente en el Drama Centre London. Comienza su carrera interpretando papeles en dramas bélicos, siendo famosa su interpretación del soldado John Janovec en la premiada miniserie Hermanos de sangre. Hace su debut cinematográfico de la mano de Ridley Martten Scott en el año 2001 en Black Hawk derribado. En 2006 tiene un papel secundario en la comentada película María Antonieta de Sophia Coppola y en 2008 en RocknRolla de Guy Ritchie. En 2009 interpreta el papel protagonista de Bronson. Pero posiblemente el filme que le catapulta a la fama internacional es Origen (Inception), con Leonardo di Caprio; su físico imponente y su vestimenta le lanzan como sex symbol. En 2011 participa en Tinker Tailor Soldier Spy (El topo), adaptación cinematográfica de la novela de John Le Carré, con un gran reparto encabezado por el veterano actor Gary Oldman en el papel de George Smiley, Colin Firth, John Hurt y Toby Jones, entre otros. En 2012 Hardy es el nuevo enemigo de Batman en Batman:The Dark Knight Rises, la última entrega de la trilogía sobre el citado héroe, abordada por el director Christopher Nolan. Hardy brinda una gran actuación interpretando al cerebral Bane.","Tom_Hardy.jpg");
INSERT INTO ACTORES (NOMBRE_APE,NACIONALIDAD,FECHA_NAC,DESCRIPCION,CARRERA,IMAGEN) VALUES ("Sylvester Stallone","EEUU","1946-07-06","Sylvester Stallone (6 de julio, 1946) es un actor, guionista y director de cine estadounidense.","Sylvester Stallone (6 de julio, 1946) es un actor, guionista y director de cine estadounidense. Sylvester Stallone, apodado 'Sly', es considerado como una de las estrellas más importantes del cine de acción de Hollywood. Ha dado vida a dos icónicos personajes del cine: Rocky Balboa, el humilde boxeador de Filadelfia que venció todos los pronósticos y ante la adversidad, se convirtió en campeón; y John Rambo, el atormentado ex boina verde veterano de la guerra de Vietnam, especializado en guerrilla, supervivencia y combate. Aparte de las sagas de Rocky y Rambo, entre sus cintas más populares se encuentran: Los Mercenarios (2010), Asesinos (1995), El Juez Dredd (1995), El especialista (1994), Demolition Man (1993), Cliffhanger (1993), Lock Up (1989), Tango y Cash (1989), Over the Top (1987) y Cobra (1986).","Sylvester_Stallone.jpg");
INSERT INTO ACTORES (NOMBRE_APE,NACIONALIDAD,FECHA_NAC,DESCRIPCION,CARRERA,IMAGEN) VALUES ("Arnold Schwarzenegger","Austria","1947-07-30","Arnold Schwarzenegger (nacido el 30 de julio de 1947 en Graz, Estiria, Austria), es un exfísico-culturista, actor y político.","Arnold Schwarzenegger (nacido el 30 de julio de 1947 en Graz, Estiria, Austria), es un exfísico-culturista, actor y político austriaco nacionalizado estadounidense que ejerció como trigésimo octavo gobernador de California desde 2003 hasta 2011. Schwarzenegger ganó fama en todo el mundo como un icono de las películas de acción de Hollywood, conocido por sus papeles protagonistas en películas como Conan el Bárbaro, Terminator, Comando, Desafío total (El vengador del futuro en Hispanoamérica) y Depredador. Fue apodado el roble austríaco y el roble de Estiria en sus días de culturismo, Arnie durante su carrera como actor y más recientemente el Governator (una contracción de Governor y Terminator). Junto con Bruce Willis, Sylvester Stallone y Demi Moore invirtió en la cadena Planet Hollywood, aunque a comienzos del año 2000 decidió no continuar,120 porque dijo que la empresa no había tenido el éxito suficiente y que quería embarcarse en otros proyectos. Una estimación conservadora de las ganancias netas de Schwarzenegger las cifran entre cien y doscientos millones de dólares. En el transcurso de los años, invirtió mucho de su dinero por lo que es difícil estimar su fortuna, sobre todo tras la crisis económica de 2008-2010. En junio de 1997, Schwarzenegger gastó treinta y ocho millones de dólares en un jet privado. Schwarzenegger dijo una vez 'El dinero no da la felicidad. Ahora tengo cincuenta millones pero ya era feliz cuando tenía cuarenta y ocho'. También dijo: 'He conseguido muchas veces hacer un millón como hombre de negocios'.","Arnold_Schwarzenegger.jpg");
INSERT INTO ACTORES (NOMBRE_APE,NACIONALIDAD,FECHA_NAC,DESCRIPCION,CARRERA,IMAGEN) VALUES ("Jason Statham","Reino Unido","1967-09-12","Jason Statham (Londres, 12 de septiembre de 1967), actor de cine británico, conocido por sus papeles en las películas de Guy Ritchie.",
"Jason Statham (Sydenham, Londres, 12 de septiembre de 1967), es un actor de cine británico, conocido por sus papeles en las películas de Guy Ritchie como Juegos, Trampas y dos Armas Humeantes, Snatch, Cerdos y Diamantes y Revólver, así como en Crank, 1 y 2, la trilogía de The Transporter, La Carrera de la Muerte, Blitz y como más reciente Los Mercenarios.
Debido al éxito conseguido en Lock, Stock and Two Smoking Barrels, volvió a unirse con Guy Ritchie para la película Snatch: cerdos y diamantes en 2000, junto a actores como Brad Pitt, Dennis Farina y Benicio del Toro.
Después de Snatch actuó en Turn It Up (2000), con el rapero estadounidense Ja Rule, seguido por papeles secundarios en Fantasmas de Marte (2001), El único (2001), con Jet Li y bajo la dirección de James Wong, y en Mean Machine (2001), junto con Vinnie Jones.
En 2002, después de realizar papeles secundarios, obtuvo finalmente un papel principal, el de Frank Martin en El Transportador. Statham también actuó en el remake de The Italian Job. Tras realizar un cameo en Colateral (2004) y trabajar en Celular (2004), en 2005 protagonizó la primera secuela de El Transportador, El Transportador 2, Revólver (esta última película también de Guy Ritchie), y también Chaos, junto con Wesley Snipes. En 2006 protagonizó la película Crank. En 2008 protagonizó la segunda secuela de El Transportador, El Transportador 3 y el remake de La Carrera de la Muerte, y en 2009 protagonizó la secuela de Crank, Crank 2: High Voltage.
En 2010 coprotagonizó, junto a Sylvester Stallone, Jet Li y Dolph Lundgren, la taquillera película de acción Los Mercenarios, dirigida por Sylvester Stallone.
En 2011 protagonizó la película El Mecánico, dirigida por Simon West, remake de la película del mismo nombre que interpretó en 1972 Charles Bronson.
En 2012 protagoniza junto a Robert De Niro, Yvonne Strahovski, y Clive Owen, la película Asesinos de Élite.
Trabajó en la secuela Los Mercenarios 2, estrenada en 2012.
","Jason_Statham.jpg");
INSERT INTO ACTORES (NOMBRE_APE,NACIONALIDAD,FECHA_NAC,DESCRIPCION,CARRERA,IMAGEN) VALUES ("Sam Worthington","Reino Unido","1976-08-02","Sam Worthington (Godalming, Surrey, Inglaterra, 2 de agosto de 1976) es un actor británico.",
"Sam Worthington (Godalming, Surrey, Inglaterra, 2 de agosto de 1976) es un actor británico.
Después de graduarse en 1998, Worthington realizó una producción sobre el Beso de Judas para la productora Company B en el Belvoir St Theatre.
Siguió actuando en una serie de Australia, en películas y series de televisión, incluyendo una función, Bootmen y actuaciones en Dirty Deeds, Gettin Square (El Desquite),Somersault y Macbeth. Worthington ganó en el 2004 el Premio al Mejor Actor Principal por su papel en Somersault. Es muy conocido en Australia por su papel de Howard en la aclamada serie de televisión australiana Love My Way.
La carrera internacional de Worthington en el cine comenzó con una serie de pequeños papeles en Hollywood en producciones como Hart's War (La Guerra de Hart) y The Great Raid, que se rodó en Australia. Fue uno de varios actores candidatos para hacer el papel de James Bond (que Pierce Brosnan había dejado) para la película de 2006 Casino Royale. El director, Martin Campbell declaró que sólo Worthington y Henry Cavill resultaron finalistas y en reñida competición con el que fue el ganador al final, Daniel Craig.
En 2007, James Cameron eligió a Worthington para el papel principal para la película Avatar. El 12 de febrero de 2008 saltó la noticia de que había sido elegido, por recomendación de Cameron, para el papel de Marcus Wright en Terminator Salvation, película ya estrenada en el mundo entero. En el 2010 puso la voz de Alex Mason, personaje principal del videojuego Call of duty: Black Ops.
Actualmente el artista se encuentra en Tenerife, Canarias (España), para la grabación de la segunda entrega de Furia de Titanes. Además, grabó un tráiler de Call of Duty: Modern Warfare 3 con Jonah Hill y Dwight Howard.
","Sam_Worthington.jpg");
INSERT INTO ACTORES (NOMBRE_APE,NACIONALIDAD,FECHA_NAC,DESCRIPCION,CARRERA,IMAGEN) VALUES ("Zoe Saldana","EEUU","1978-06-19","Zoe Saldana (Passaic, New Jersey el 19 de junio de 1978). Su padre, Aridio Saldaña, es dominicano y su madre Asalia Nazario puertorriqueña.",
"Zoe Saldana (Passaic, New Jersey el 19 de junio de 1978). Su padre, Aridio Saldaña, es dominicano y su madre Asalia Nazario puertorriqueña.
Saldana todavía era miembro del grupo teatral Faces cuando consiguió espacio en un episodio de Law & Order (titulado 'Merger') que se emitió por primera vez en 1999. Dejó la escuela después de su participación en la película Center Stage, apareciendo posteriormente junto a Britney Spears en Crossroads y en la comedia-dramática Drumline (2002). Desempeñó el papel de la pirata Anamaría en la película de 2003 Piratas del Caribe: La Maldición de la Perla Negra, y ha aparecido en películas como The Terminal junto a Tom Hanks (2004) y Guess Who (2005), con Ashton Kutcher. Ese mismo año protagonizó la película dominicana La maldición del padre Cardona junto a personalidades dominicanas como Freddy Beras Goico, Anthony Álvarez y Sergio Carlo.
Saldana también fue la protagonista en el video para la canción de Juan Luis Guerra 'La Llave De Mi Corazón', e interpretó a Uhura en la secuela de 2009 de la saga Star Trek. Además ese año interpretó a Neytiri, la princesa Na'vi, de la película Avatar de James Cameron, un papel que le dio mucha publicidad y reconocimiento, y por lo tanto oportunidades para trabajar en grandes producciones comerciales.
Zoe es la única actriz, que ha estado en tres películas consideradas entre las más taquilleras, en tres semanas consecutivas. Estas películas son Avatar, The Losers, y Death at a Funeral.
En agosto de 2010, se estrenó un anuncio de televisión de Saldaña para la marca Calvin Klein haciendo el debut de un producto llamado 'Envy'. En 2011, protagonizó el crimen-dramático Colombiana.
","Zoe_Saldana.jpg");
INSERT INTO ACTORES (NOMBRE_APE,NACIONALIDAD,FECHA_NAC,DESCRIPCION,CARRERA,IMAGEN) VALUES ("Sigourney Weaver","EEUU","1949-10-08","Sigourney Weaver (8 de octubre de 1949, Nueva York, Estados Unidos) es una actriz y productora estadounidense de cine, televisión y teatro.",
"Sigourney Weaver (8 de octubre de 1949, Nueva York, Estados Unidos) es una actriz y productora estadounidense de cine, televisión y teatro.
Candidata a los Premios Óscar y a los Premios del Sindicato de Actores. Ganadora de dos Globo de Oro en las categorías de mejor actriz en drama y mejor actriz de reparto. Asimismo también ganadora de un BAFTA a la mejor actriz de reparto. Conocida por sus intervenciones como la Teniente Ripley en Alien (1979), Aliens (1986), Alien 3 (1992) y Alien Resurrection (1997). Ha participado en películas como Ghostbusters (1984), Gorilas en la niebla (1988), Working Girl (1988), The Village (2004) y Avatar (2009). También conocida como la 'reina de la ciencia-ficción'.
","Sigourney_Weaver.jpg");
INSERT INTO ACTORES (NOMBRE_APE,NACIONALIDAD,FECHA_NAC,DESCRIPCION,CARRERA,IMAGEN) VALUES ("Ben Affleck","EEUU","1972-08-15","Benjamin Geza 'Ben' Affleck (Berkeley, California; 15 de agosto de 1972) es un actor, productor, guionista y director estadounidense.",
"Benjamin Geza 'Ben' Affleck (Berkeley, California; 15 de agosto de 1972) es un actor, productor, guionista y director estadounidense. 
Se dio a conocer con sus actuaciones en las películas de Kevin Smith tales como Persiguiendo a Amy (1997) y Dogma (1999). Affleck ganó un Óscar y un Globo de Oro por el guion de Good Will Hunting (1997), que él co-escribió con Matt Damon, y ha aparecido en papeles principales en éxitos populares como Armageddon (1998), Pearl Harbor (2001), Changing Lanes (2002), The Sum of All Fears (2002), Daredevil (2003), o films de temática más seria como Hollywoodland (2007), La sombra del poder (2009) y The Town (2010). Affleck es un director de cine aclamado por la crítica. Dirigió Gone Baby Gone (2007),The Town (2010) y Argo (2012) desempeñando el papel principal en los dos últimos. La dirección y participación en Argo le valió un Óscar por Mejor Película, 2 Globos de Oro, 2 Premios BAFTA y el premio de Mejor Director del Sindicato de Directores entre otros galardones.
","Ben_Affleck.jpg");
INSERT INTO ACTORES (NOMBRE_APE,NACIONALIDAD,FECHA_NAC,DESCRIPCION,CARRERA,IMAGEN) VALUES ("Bryan Cranston","EEUU","1956-03-07","Bryan Cranston (nacido el 7 de marzo de 1956 en Valle de San Fernando, California) es un actor, escritor y director estadounidense.",
"Bryan Cranston (nacido el 7 de marzo de 1956 en Valle de San Fernando, California) es un actor, escritor y director estadounidense.
Su personaje más popular lo interpretó en la serie Malcolm in the middle, interpretando a Hall Wilkerson, (padre de Malcolm) en el año 2000 y sucesivos.
Antes de su papel en Malcolm, interpretó al astronauta Buzz Aldrin en la serie de HBO From the Earth to the Moon (HBO). También interpretó el papel del astronauta Gus Grissom en la película That Thing You Do!. También realizó un papel secundario en la serie Seinfeld, como el doctor Tim Whatley, el dentista de Jerry. Varios episodios están basados en la relación de Jerry con su dentista y su paranoia hacia los dentistas. Adicionalmente, ha tenido un papel en la comedia The King of Queens como Tim Sasky, un vecino molesto de Doug Heffernan; y en la serie Como conocí a vuestra madre como Hammond Druthers, un compañero de trabajo también molesto de Ted Mosby . Actualmente encarna al protagonista de la serie Breaking Bad, donde interpreta a un profesor de química que se introduce en el mundo del narcotráfico.
En la película de Steven Spielberg Saving Private Ryan interpreta el papel de oficial en el Departamento de Guerra al inicio de la película y en la película Little Miss Sunshine interpreta al agente literario de Greg Kinnear.
Cranston ha dirigido episodios de algunas de las diversas series en las que ha participado y ha recibido tres Premios Emmy por su papel de Walter White en la aclamada serie Breaking Bad . Además escribió y dirigió la película Last Chance, estrenada en 1999.
En el año 2011 vuelve al cine con la película 'El Inocente' con el papel del detective Lankford y en 'El vengador del futuro'.
En 2012 interpreta a Jack O'Donnell en la película Argo considerada como una de las mejores películas del 2012, ganadora del Oscar a la mejor película de dicho año.
","Bryan_Cranston.jpg");







INSERT INTO ACTORES (NOMBRE_APE,NACIONALIDAD,FECHA_NAC,DESCRIPCION,CARRERA,IMAGEN) VALUES ("Martin Freeman","Reino Unido","1971-09-08","Martin John C. Freeman (8 de septiembre de 1971) es un actor británico.",
"Martin John C. Freeman (n. Aldershot, Hampshire; 8 de septiembre de 1971) es un actor británico conocido por su papeles en la película Guía del autoestopista galáctico (2004) y las series The Office (2001-2003) y Sherlock (2010-¿?). El 14 de diciembre de 2012 estrenó El hobbit: un viaje inesperado, película en la cual interpreta al famoso Hobbit Bilbo Bolsón, en 2013 y 2014 estrenará sus secuelas. Siendo el menor de los cinco hijos de una ama de casa con vocación de actriz llamada Philomena y un oficial de la Marina llamado Geoffrey, Martin Freeman se fue a vivir con su padre cuando el matrimonio se separó. Poco tiempo después su padre murió de un infarto y Martin se trasladó con su madre y su padrastro a Teddington. Allí estudió en una escuela secundaria católica y entre los nueve y los catorce años formó parte del equipo nacional británico de squash, a pesar
de su estado enfermizo (padecía asma y era propenso a los desmayos). Tras dejar este deporte, se unió a un grupo de teatro local y asistió a la Central School of Speech and Drama. El público conoce a Freeman principalmente por interpretar el personaje central de Arthur Dent en Guía del autoestopista galáctico (The Hitchhiker's Guide to the Galaxy, 2005), y como Tim en la exitosa serie cómica de la BBC, The Office (2001-2003). Para televisión, también ha participado en la miniserie Charles II: The Power and The Passion (2003) y en las series The Robinsons (2005), para la BBC, Hardware (2003-2004), para la ITV, y Sherlock (2010-presente), para la BBC. Entre los títulos cinematográficos en su haber, cabe citar Ali G anda suelto (Ali G Indahouse, 2002); Love Actually (2003); Confetti (2006); Arma fatal (Hot Fuzz, 2007), dirigida por Edgar Wright, responsable de
Zombies Party (Shaun of the Dead, 2004); Breaking and Entering (2006), de Anthony Minghella; The Good Night (2007); y de la mano de Peter Jackson las tres películas basadas en la novela El hobbit, donde interpreta a Bilbo Bolsón, y cuyo estreno se realizó a finales de 2012 (El hobbit: un viaje inesperado), para finales de 2013 (El hobbit: la desolación de Smaug) y verano boreal de 2014 (El hobbit: partida y regreso). Martin también disfruta de una carrera teatral de perfil alto, con piezas en su haber con Kathy Burke en la Royal Court Theatre; participando en Blue Eyes & Heels, en el Soho Theatre, que agotó todas las entradas; y en la muy reconocida The Exonerated, en los Riverside Studios, en 2006.
","Martin_Freeman.jpg");


INSERT INTO ACTORES (NOMBRE_APE,NACIONALIDAD,FECHA_NAC,DESCRIPCION,CARRERA,IMAGEN) VALUES ("Ian McKellen","Reino Unido","1939-05-25","Sir Ian Murray McKellen, CH, CBE (n. Burnley, Lancashire; 25 de mayo de 1939), es un actor británico de teatro y cine, nominado al Óscar en dos ocasiones.",
"Aunque nació en Burnley, McKellen pasó la mayor parte de su infancia en la localidad de Wigan, acudiendo más tarde a la Bolton School. Sus cuatro primeros años de vida transcurrieron bajo la amenaza de los bombardeos nazis de la Segunda Guerra Mundial, que según sus propias declaraciones, tuvieron un fuerte impacto psicológico en él. Estudió en la Bolton School, en el área metropolitana de Mánchester, y más tarde terminó sus estudios de interpretación en la Universidad de Cambridge. La familia McKellen profesaba una fuertemente arraigada fe cristiana, aunque no excesivamente puritana. Su madre (Margery Lois) falleció teniendo él 12 años y su padre (Denis Murray) se volvió a casar. Éste falleció cuando Ian contaba con 24 años, tras lo cual siguió manteniendo una buena relación con su madrastra, a la que confesó su homosexualidad. Según las palabras de McKellen, la viuda
de su padre se mostró más contenta que disgustada, ya que sabía que Ian había dejado de mentir sobre su orientación sexual. Comenzó una relación con su primer compañero sentimental, Brian Taylor, en 1964, con quien vivió en Londres hasta 1972, cuando la relación terminó. En 1978 conoció al hombre con el que tendría su segunda relación seria en el Festival de Edimburgo. Su nombre era Sean Mathias, también actor, y tuvieron una relación algo agitada. Sus discusiones parecían tener muchas veces su raíz en la, por alguna razón, menos aclamada carrera de Mathias, que achacaba su poco éxito a su relación con Ian McKellen; aun así, también reconocía que él había intentado ayudarle siempre. Esta relación duró 10 años. McKellen ha trabajado en el cine durante toda su carrera como actor desde 1966. Sin embargo, fue en los años 1990 cuando sus apariciones comenzaron a ser más
reseñables y significativas, con participaciones en proyectos que consiguieron éxito mundial, incluyendo películas como Sacerdote del amor (Christopher Miles, 1981), Walter (Stephen Frears, 1982), The Keep (Michael Mann, 1983), Plenty (Fred Schepisi, 1985) y Cold Comfort Farm (John Schlesinger, 1995). Su carrera siguió en cualquier caso supeditada a las más de 250 obras de teatro en las que ha actuado a lo largo de casi cincuenta años. Una de ellas, Ricardo III de William Shakespeare, se estrenó en el National Theatre de Londres, fue de gira por Europa y Estados Unidos y la adaptó al cine el propio McKellen, que ganó por este papel el premio Félix al mejor actor europeo del año en 1996 y una nominación al Globo de Oro. La película fue dirigida por Richard Loncraine. En 1993, McKellen interpretó un papel secundario en Seis grados de separación, donde trabajó junto a Donald
Sutherland, Will Smith y Stockard Channing; pero su salto al panorama internacional fue cuando interpretó al director de Frankenstein, James Whale, en la película Dioses y monstruos, por la que fue nominado al Óscar al mejor actor. En 2000 aceptó trabajar en la trilogía de El Señor de los Anillos, interpretando al mago Gandalf, papel por el que también recibió una nominación al Óscar al mejor actor de reparto. En 2011 volvió a rodar como el mago Gandalf en las películas de Peter Jackson basadas en El hobbit. Durante unos años trabajó en el cine en películas como la trilogía de X-Men, de Bryan Singer (con quien ya había participado unos años antes en Apt Pupil) y Brett Ratner, basado en las famosas historietas del mismo título, interpretando al famoso villano Magneto; también en El código Da Vinci (2006) de Ron Howard, basada en el libro de Dan Brown, interpretando a Leigh
Teabing, un hábil y obsesionado historiador. Tras la muerte del actor irlandés Richard Harris, se le ofreció el papel de Albus Dumbledore en la serie de películas de Harry Potter, pero lo rechazó ya que no quería mezclar su papel de Gandalf con el de Dumbledore, por lo que el papel pasó al actor Michael Gambon. Ian McKellen en Europride, en Mánchester (2003). En 2006, el Festival Internacional de Cine de Berlín le entregó un Oso de oro honorífico por toda su carrera. En 2009 se le concedió el Premio Donostia, premio a toda la carrera concedido en el ámbito del Festival Internacional de Cine de San Sebastián.
","Ian_McKellen.jpg");


INSERT INTO ACTORES (NOMBRE_APE,NACIONALIDAD,FECHA_NAC,DESCRIPCION,CARRERA,IMAGEN) VALUES ("Suraj Sharma","India","1993-03-21","Suraj Sharma (n. Nueva Delhi, 21 de marzo de 1993), es un actor indio que se dio a conocer en 2012 por su protagonismo en la película estadounidense La Vida de Pi.",
"Suraj Sharma (n. Nueva Delhi, 21 de marzo de 1993), es un actor indio que se dio a conocer en 2012 por su protagonismo en la película estadounidense La Vida de Pi, dirigida por el director Ang Lee. Este filme se basó en la novela La vida de Pi de Yann Martel. Suraj nació en el seno de una familia keralite (malayali). Estudió en la escuela Sardar Patel Vidyalaya de Nueva Delhi. Su padre es ingeniero y su madre economista, ambos oriundos de Kerala (de Thalassery y Palakkad, respectivamente). Antes de la película, no tenía ninguna relación con el mundo cinematográfico ni tampoco había estudiado ninguna carrera artística. Sin embargo, Ang Lee lo escogió para el papel de actor principal entre otros 3000 candidatos por su apariencia inocente, su mirada profunda y su complexión física tan semejante a la de Pi. Suraj ha declarado que se presentó al casting porque su hermano menor
lo animó a ello. Suraj ha recibido el Premio Joven de la sociedad de críticos de Las Vegas. Además, ha sido nominado a un BAFTA, un NAACP Image Awards7 y un Critic's Choice Awards.8 Tras la película, Suraj ha retomado sus estudios en la carrera de filosofía de la Universidad de Delhi y pretende seguir con su futuro cinematográfico.
","Suraj_Sharma.jpg");


INSERT INTO ACTORES (NOMBRE_APE,NACIONALIDAD,FECHA_NAC,DESCRIPCION,CARRERA,IMAGEN) VALUES ("Daniel Craig","Reino Unido","1968-03-02","Daniel Wroughton Craig (n. 2 de marzo de 1968) es un actor británico conocido especialmente por interpretar en el cine al personaje de Ian Fleming James Bond.",
"Daniel Wroughton Craig (n. 2 de marzo de 1968) es un actor británico conocido especialmente por interpretar en el cine al personaje de Ian Fleming James Bond. A finales de 2012, es el sexto y último actor en interpretar el papel de James Bond en las adaptaciones oficiales de las películas producidas por EON Productions como Casino Royale, Quantum of Solace (2008) y Skyfall (2012). El actor, forjado en la compañía británica Teatro Nacional de la Juventud (National Youth Theatre), se graduó en la Escuela Guildhall de Música y Drama de Londres donde comenzó su carrera en el escenario. Debutó en el cine con La fuerza de Uno (1992), a la cual siguieron otras interpretaciones en películas como Elizabeth y Las Aventuras en la corte del Rey Arturo, en televisión participó en El Zorro y El águila de Sharpe. Actuaciones en el cine británico como las de Love is the Devil, La
trinchera o Algunas voces atrajeron la atención de la industria sobre él haciéndole llegar papeles de más calado internacional como la versión cinematográfica del videojuego Lara Croft: Tomb Raider (2001), Layer Cake (2004), o las nominadas al Óscar Camino a la perdición (2002) de Sam Mendes y Munich (2005) de Steven Spielberg. Craig alcanzó la fama internacional cuando fue elegido como el sexto actor para interpretar el papel de James Bond, en sustitución de Pierce Brosnan. Aunque inicialmente recibido con escepticismo, su debut en Casino Royale fue muy aclamado por la crítica y le valió una nominación al premio BAFTA, consiguiendo además que Casino Royale fuera la película más taquillera de la franquicia hasta esa época. En 2006 pasó a formar parte de la Academia de Artes y Ciencias Cinematográficas. Daniel Craig está casado en segundas nupcias con Rachel Weisz
y tiene una hija de su anterior matrimonio. En la lista Top 40 celebridades de Hollywood con más ingresos a lo largo de 2010 que publicó Vanity Fair, Craig ocupaba la posición 28 con unas ganancias estimadas en unos 18 millones de dólares por sus películas. Según una encuesta realizada por la empresa de preservativos Durex Play, que entrevistó a 4.000 británicas[cita requerida], Craig es el hombre más sexy del mundo. Pese al hecho de que el personaje de James Bond ha eclipsado prácticamente el resto de su carrera, cabe destacar su faceta en el teatro británico donde ya despuntaba como joven promesa en el Teatro Juvenil Nacional. Es uno de los rostros más conocidos de los que han alcanzado la fama partiendo de esta humilde base teatral británica. Desde los 14 años, ha interpretado papeles en obras como Oliver!, Romeo y Julieta y Cenicienta mientras estaba en la
Hilbre High School. Con 16 años, ya en el Teatro Juvenil Nacional, debutó como Agamemnon en la obra de Shakespeare Troilo y Crésida. También ha realizado papeles para la televisión como Arcángel, Copenhagen o Sword of Honour (Espada de honor, una trilogía de la Segunda Guerra Mundial). Así mismo, al margen de su papel como James Bond, en su filmografía figuran títulos tan ilustres como Layer Cake: crimen organizado (2004) para la que fue nominado como mejor actor en los Premios del Cine Europeo y los Empire británicos; Love is the Devil (1998), película biográfica sobre el pintor Francis Bacon; Elizabeth, protagonizada por Cate Blanchett; las nominadas a los Óscar Munich de Steven Spielberg y Camino a la perdición de Sam Mendes.
También participó en el filme Lara Croft: Tomb Raider junto a Angelina Jolie interpretando al personaje Alex West. A principios de febrero de 2005, Craig fue nombrado por los diferentes medios informativos como un posible candidato para reemplazar a Pierce Brosnan como James Bond. El 6 de abril del mismo año, se informó que Craig había firmado con EON Productions un contrato de cuatro películas con un valor de 15 millones de libras. Sin embargo, esta noticia fue luego refutada por la BBC quienes contactaron a EON para un informe oficial. De acuerdo con Craig, la MGM le ofreció el papel pero la familia Broccoli nunca lo contactó. Finalmente, el 14 de octubre del 2005, Producciones EON nombró a Daniel Craig como el sexto actor en interpretar a 007, reemplazando a Pierce Brosnan. Craig firmó un contrato de cuatro películas. La primera fue Casino Royale, estrenada
mundialmente el 17 de noviembre del 2006. El anuncio fue hecho a mediodía en Londres, en el buque HMS President, actualmente una estación de la Reserva de la Marina Real (RNR) en el Muelle de St. Katharine, debajo del Puente de la Torre en el río Támesis. Daniel Craig, interpretando a James Bond en sus películas oficiales, es el primer Bond rubio, el primero nacido (1968) después de la franquicia fílmica (1962) y el primero después la muerte de su creador, Ian Fleming (1964). Cuatro de los últimos actores que han interpretado a Bond (Sean Connery, Roger Moore, Timothy Dalton y Pierce Brosnan) han indicado que Craig es una buena opción como Bond.
","Daniel_Craig.jpg");



INSERT INTO ACTORES (NOMBRE_APE,NACIONALIDAD,FECHA_NAC,DESCRIPCION,CARRERA,IMAGEN) VALUES ("Javier Bardem","España","1969-03-01","Javier Ángel Encinas Bardem (Las Palmas de Gran Canaria, Gran Canaria, España, 1 de marzo de 1969), más conocido como Javier Bardem, es el primer actor español que estuvo nominado a un premio Óscar.",
"Javier Ángel Encinas Bardem (Las Palmas de Gran Canaria, Gran Canaria, España, 1 de marzo de 1969), más conocido como Javier Bardem, es el primer actor español que estuvo nominado a un premio Óscar y el primero en ganarlo ocho años más tarde por su papel en No Country for Old Men (2008). Además, ha ganado seis Goyas, un Globo de Oro, un BAFTA, el premio del Festival de Cannes al mejor actor y un premio del Sindicato de Actores. Está casado con la actriz Penélope Cruz, con la que ha trabajado en Jamón, jamón, Carne trémula y Vicky Cristina Barcelona. El primer hijo del matrimonio, llamado Leo, nació el 22 de enero de 2011 en Los Ángeles. Nacido en el barrio de San Nicolás en Las Palmas de Gran Canaria, hijo de José Carlos Encinas Doussinague de origen cubano español y Pilar Bardem, Bardem desciende de una saga de actores: sus abuelos Rafael Bardem y Matilde Muñoz
Sampedro, su madre Pilar y su hermano mayor Carlos son un ejemplo. Pero también su tío Juan Antonio Bardem y su primo Miguel han destacado como directores de cine. Aun así, Javier empezó en las categorías inferiores de la selección española de Rugby y llegó a jugar hasta 1990 con el CR Liceo Francés de Madrid en las posiciones de pilier y tercera línea hasta la categoría senior antes de estudiar Pintura en la Escuela de Artes y Oficios y continuar con su formación en Juan Carlos Corazza, estudio con el que sigue vinculado a día de hoy. Con solo cuatro años, Bardem hizo un papel pequeño en la serie de televisión El pícaro (1974), aunque no aparece en los créditos. Su primera escena como actor estuvo marcada por una anécdota con Fernando Fernán Gómez. Según explica el artista, en la secuencia Fernán Gómez le apuntaba con una pistola y él tenía que reirse. En cambio,
se asustó y lloró. Su compañero de trabajo le quitó peso a la situación y exclamó: 'No pasa nada, dejadle, es un actor dramático'. Con 11 años, Bardem tuvo un pequeño papel en la película protagonizada por su madre El poderoso influjo de la Luna, dirigida por Antonio del Real. En la segunda mitad de la década de 1980, realizó apariciones esporádicas en Televisión Española, como en un capítulo de las series Segunda enseñanza (1986) y Brigada central (1989), ambas de Pedro Masó o colaborando con el magazín El día por delante (1989), dirigido y presentado por Pepe Navarro. Los años pasaron y su físico es muy apropiado para interpretar personajes agresivos y rudos. Tras una breve aparición en la polémica Las edades de Lulú (Bigas Luna, 1990), se convirtió en uno de los actores fetiche de este director y por eso, junto a la que 18 años después se convertiría en su mujer
Penélope Cruz y Jordi Mollá, protagonizó Jamón, jamón (1992), película que catapultaría al trío a la fama. Ganó, en 1994, el Fotogramas de Plata al Mejor Actor por Huevos de oro, de Bigas Luna, el Premio a Mejor actor en el Festival de San Sebastián por Días contados y El detective y la muerte y el Premio Fernando Rey a la Mejor Interpretación por Días contados. Un año más tarde, y por esta última película, consiguió el Goya al Mejor Intérprete Masculino de Reparto y el Premio de la Unión de Actores al Mejor Actor, además del Fotograma de Plata por Boca a boca, gracias a la cual ganó el Goya a la Mejor interpretación masculina protagonista en 1996. Después de conseguir en diciembre de 1997 el Premio del Público al Mejor Actor en la Gala de la Academia de Cine Europeo, en enero de 1998 compite por el Goya a la Mejor Interpretación Masculina por Carne trémula. En 1999
volvería a trabajar con Mollá en Segunda piel. En 2003 obtuvo el Goya a la Mejor Interpretación Masculina protagonista por su papel en Los lunes al sol, compartiendo protagonismo con Luis Tosar, también ganador de un Goya por esta película. En la ceremonia de entrega de dicho premio hace oír su voz contra la guerra y la invasión de Irak. En 2004 consiguió nuevamente la Copa Volpi en el Festival de Cine de Venecia , esta vez por su papel en Mar adentro, por el que también repitió el Goya al Mejor actor. En 2006 protagonizó El amor en los tiempos del cólera, dirigida Mike Newel con un guion del sudafricano Ronald Harwood y rodada en Cartagena de Indias. En 2008 protagonizó, junto a entre otras Scarlett Johansson y la que tres años después sería su mujer Penélope Cruz, Vicky Cristina Barcelona, dirigida por el neoyorkino Woody Allen. En 2008 ganó un Globo de oro al
mejor actor de reparto por su actuación en la película No Country for Old Men de los hermanos Coen. También, por esta misma película, ganó el BAFTA al mejor actor de reparto y finalmente el Óscar en la misma categoría, siendo el primer actor español que gana tal premio. Tras recibir el premio, agradeció públicamente a su maestro Corazza su ayuda para componer el personaje. Este mismo año es galardonado con el Premio Nacional de Cinematografía. Entre sus últimos proyectos está Biutiful con el que ha ganado el Goya al mejor actor protagonista. Bardem se ha erigido en los últimos años en defensor del pueblo saharaui y su derecho a la autodeterminación que posee este pueblo, antigua colonia española. El 8 de noviembre de 2012 Javier estrenó su estrella en el Paseo de la Fama de Hollywood. En enero de 2013, la Academia Británica de Cine anunció la candidatura a los
Premios BAFTA de Bardem en la categoría de actor secundario por su papel en el filme 'Skyfall'. En febrero de 2013 Javier y Penélope confirman que esperan su segundo hijo.
","Javier_Bardem.jpg");



INSERT INTO ACTORES (NOMBRE_APE,NACIONALIDAD,FECHA_NAC,DESCRIPCION,CARRERA,IMAGEN) VALUES ("Naomi Watts","Reino Unido","1968-09-28","Naomi Watts (28 de Septiembre de 1968; Shoreham Kent, Reino Unido) es una actriz nacida en Reino Unido pero de nacionalidad australiana. Watts comenzó su carrera en la televisión australiana.",
"Naomi Watts (28 de Septiembre de 1968; Shoreham Kent, Reino Unido) es una actriz nacida en Reino Unido pero de nacionalidad australiana. Watts comenzó su carrera en la televisión australiana, donde apareció en anuncios y series, incluyendo la telenovela Home and Away, la galardonada miniserie Novias de Cristo y en la comedia ¡Oye, papá ...! En el cine Watts es conocida por sus papeles en las películas Mulholland Drive (2001), donde se dio a conocer al gran público, The Ring (2002), 21 gramos (2003), que fue nominada a dos Premios de la Academia, King Kong (2005), donde actuó junto con Jack Black y Adrien Brody, y más recientemente en The International (2009). Ha trabajado con directores de la talla de David Lynch, Peter Jackson, Woody Allen, Clint Eastwood o el español Juan Antonio Bayona. En el 2013 fue nominada por segunda vez al Oscar a la mejor actriz por su papel en Lo imposible.
Watts nació en Shoreham, Kent en Inglaterra, donde vivió hasta los ocho años. Sus padres, Gilette Edwards Braun (una galesa vendedora de antigüedades y diseñadora de ropa) y Peter Watts (un inglés chapero de giras e ingeniero de sonido del grupo Pink Floyd, quién aparece en la caratula trasera del álbum 'Ummagumma' con camisa blanca), se separaron cuando ella tenía cuatro años.
Poco después, su madre se trasladó con el resto de la familia a la localidad de Llangefni (concretamente a uno de sus distritos llamado Llanfawr), al noroeste de Gales, donde vivirían con sus abuelos Hugh y Nikki Roberts. Aunque su madre se trasladaba algunas veces a Gales e Inglaterra, normalmente por sus noviazgos, siempre terminaba volviendo a Llangefni. Al cumplir los catorce años y durante un viaje a Australia, su madre se dio cuenta de que era 'la tierra de las oportunidades' y se trasladaron a Sídney en 1982. Su abuela, Nikki, era australiana, así que no fue difícil obtener la documentación necesaria; desde entonces Naomi y su familia son ciudadanos australianos. Naomi describe a su madre como una hippie con tendencias 'pasivo-agresivas' que amenazaba con enviarla junto con su hermano Ben (un año mayor que ella y ahora fotógrafo en los Estados Unidos) al cuidado de sus abuelos,
pues no tenía dinero para poder hacerse cargo de ellos, después de la muerte de su padre. Una vez en Sídney, asistió a la High school de Mosman. Fue a varios institutos, incluyendo el North Sydney Girls High School donde fue compañera de clase de Nicole Kidman, de la que todavía es buena amiga. En 1986 hizo un paréntesis en la interpretación y se marchó a Japón para trabajar como modelo, pero la experiencia, que duró unos cuatro meses, fue poco fructífera ya que Watts no tenía los requerimientos físicos necesarios para ser una modelo de pasarela y debía conformarse con trabajar en promociones, las cuales no le gustaban mucho. Watts dice que fue una de las peores etapas de su vida. Tras regresar a Australia, se fue a trabajar a unos grandes almacenes y después trabajó como asistente de moda para una revista de moda Australiana. Una invitación casual para trabajar en un taller de teatro
reactivó su pasión por la actuación, y la motivó a dejar su trabajo y dedicarse a la interpretación. Watts inició su carrera en series de televisión australianas, incluidas Home and Away, Brides of Christ y Hey Dad..!.. Además tuvo un papel secundario en la película australiana de 1991 Flirting junto con las por aquel entonces futuras estrellas de Hollywood Nicole Kidman y Thandie Newton. También tuvo un papel secundario en Tank Girl, en 1995. En 1998 apareció en la película Dangerous Beauty, en un papel secundario, interpretando a 'Guila de Lezze', pero el reparto contaba con estrellas de la talla de Catherine McCormack, Rufus Sewell o Jacqueline Bisset. Anduvo buscando papeles de calidad en Hollywood y finalmente actuó en series de bajo presupuesto como Sleepwalkers, Children of the Corn IV. Empezó a conseguir papeles para películas de Hollywood. Apareció en Mulholland Drive, película
que la alzó a la fama y que se estrenó en 2001 en el Festival de Cine de Cannes, ganando la de la Sociedad Nacional de Críticos de Cine a la mejor actriz y el National Board of Review como premio Breakthrough Performance del año. La película surrealista generando controversia con un tema lésbico fuerte. y en The Shaft, dirigida por Dick Maas, que obtuvo malas críticas. Habiendo trabajado con el director/guionista Scott Coffey en Mulholland Drive, Watts y él quedaron para trabajar juntos en la película Ellie Parker (2001). En 2002, Watts protagonizó la película de terror, The Ring, un remake americano de la película japonesa. El año siguiente protagonizó la película Ned Kelly, junto con Heath Ledger, Orlando Bloom y Geoffrey Rush, además apareció en Le Divorce, junto con Kate Hudson. Luego, en 2003, protagonizó 21 gramos, de Alejandro González Iñárritu junto a Benicio del Toro y Sean Penn
y donde ganó varias nominaciones a los Premios Óscar y Premio BAFTA a la mejor actriz. En 2004 Watts tuvo un papel de apoyo en la película Extrañas coincidencias, donde actuó junto con la actriz Isla Fisher y Jude Law. Poco después, produjo y protagonizó We don't live here anymore, que fue bien acogida por los críticos. También actuó en El asesinato de Richard Nixon junto a Don Cheadle y de nuevo Sean Penn. Más tarde y en 2005, tras pasar mucho tiempo rodando King Kong, finalmente llegó a los cines. Dirigida por Peter Jackson, ha sido la película más comercial de Watts en toda su trayectoria cinematográfica. Ese mismo año rechazó el papel que le ofrecieron en Fantastic Four, y que posteriormente interpretaría Jessica Alba.
En 2006 protagonizó El velo pintado, un film dirigido por John Curran y con un reparto compuesto por Edward Norton y Liev Schreiber.
En 2007 se estrenó Promesas del este, un drama dirigido por David Cronenberg y que Watts protagoniza junto a Viggo Mortensen y Vincent Cassel. Durante el rodaje de la misma, descubrió que estaba embarazada de su primer hijo.
Fue en 2008 cuando se estrenó el remake Funny Games, dirigido por Michael Haneke, el mismo que dirigió la original. En el remake también actúa Tim Roth.
Y en abril de 2009 se estrenó The International - Dinero en la sombra, un thriller protagonizado por Watts y Clive Owen.
Además, la prensa le llama 'La reina de los remakes' ('The queen of remakes' en inglés), puesto que ha aparecido en un montón de ellos. Actualmente tienen en marcha el remake de Los pájaros (1963) de Alfred Hitchcock y la han llamado para interpretar el papel que antaño interpretó Tippi Hedren.
","Naomi_Watts.jpg");



INSERT INTO ACTORES (NOMBRE_APE,NACIONALIDAD,FECHA_NAC,DESCRIPCION,CARRERA,IMAGEN) VALUES ("Ewan McGregor","Escocia","1971-03-31","Ewan Gordon McGregor (nacido el 31 de marzo de 1971 en Crieff, Escocia) es un actor de cine y televisión británico más conocido por interpretar al Caballero Jedi Obi-Wan Kenobi.",
"Ewan Gordon McGregor (nacido el 31 de marzo de 1971 en Crieff, Escocia) es un actor de cine y televisión británico más conocido por interpretar al Caballero Jedi Obi-Wan Kenobi en los tres primeros episodios de la saga de George Lucas, Star Wars. McGregor también ha actuado como la contraparte masculina en películas románticas de Hollywood como Moulin Rouge! y Abajo el amor ambas con gran aceptacion del publico, aunque su interpretación más venerada y la que lo lanzó a la fama fue la de Mark Renton, el protagonista antihéroe de la película de culto Trainspotting de Danny Boyle. En 2005 interpretó a un psiquiatra en la película Stay de Marc Foster y en 2006 personificó a Ian Rider en la adaptación de la serie de libros de Alex Rider, la película se tituló Stormbreaker y fue dirigida por Geoffrey Sax. Ha participado en la superproducción Ángeles y demonios, junto
a Tom Hanks. También es cantante. McGregor está casado con Eve Mavrakis, una diseñadora francesa, desde 1995 con quien tiene tres hijas biológicas: Clara Mathilde, nacida en febrero de 1996, Esther Rose, nacida el 7 de noviembre de 2001, y Anouk, nacida en enero de 2011 y adoptó otra hija, Jamiyan en 2006.
Ewan McGregor nació en Crieff, Escocia en 1971. Asistió desde 1988 a la Guildhall School of Music and Drama para estudiar arte dramático. Seis meses antes de graduarse, consiguió un papel protagonista en la serie de 6 capítulos Lipstick on your Collar de Dennis Potter, en la BBC. Desde entonces ha trabajado continuamente. Su debut en el cine fue en 1993 con el film Being Human junto a Robin Williams. Su trabajo recibiría buenas críticas y ganó al año siguiente el premio Empire Award por su actuación en el thriller Shallow Grave, en el cual trabajó por primera vez con el director Danny Boyle. Este último le dirigiría también en la película Trainspotting de 1996, dándole prestigio internacional al actor, quien interpretó a Mark Renton, un adicto a la heroína en esta historia, desarrollada en Edimburgo y Londres.
Ewan McGregor ha actuado como protagonista en películas románticas de Hollywood como en la película musical Moulin Rouge!, donde demostró su capacidad a la hora de cantar, siendo la banda sonora del film un éxito mundial y por la que obtuvo una nominación al Globo de Oro como mejor actor de comedia o musical. Otra película romántica de su historial es Abajo el amor (Down With Love), y también participó en las producciones británicas Little Voice y Young Adam junto a la actriz Tilda Swinton.
Ewan McGregor dio el salto a la categoría de estrella al aceptar el papel del joven Obi-Wan Kenobi en los Episodios I, II y III de la saga Star Wars (La Guerra de las Galaxias), siendo el mismo personaje que interpretó Alec Guinness en los Episodios IV, V y VI, entre 1977 y 1983, con una apariencia anciana. Teniendo por tanto un personaje de referencia a seguir, McGregor tuvo especial cuidado en actuar de un modo lo más parecido posible al personaje interpretado por Guinness, con la misma manera de expresarse, desenvolverse e incluso de hablar. Durante el rodaje de los Episodios I, II y III (entre 1999 y 2005) el director George Lucas tuvo que sustituir momentáneamente la voz de Ewan por la de un doble cuando el acento difería mucho del original.
Tras rodar The Pillow book (El Libro de cabecera) en 1996, McGregor realizó el papel de bisexual en Velvet Goldmine en 1998, y más tarde en Scenes of a Sexual Nature en 2006. Ha sido uno de los pocos actores masculinos en prestarse a rodar escenas de desnudo frontal, por lo que se ha convertido en un icono gay. En 2003 participó en el documental Faster sobre el mundo del motociclismo, apareciendo junto a Valentino Rossi, Max Biaggi, Carlos Checa y demás competidores.
En 2005, Ewan prestó su talentosa voz a dos exitosas películas de animación. Suya es la voz del robot Rodney Copperbottom en el film Robots junto a las voces de Halle Berry y Robin Williams. Asimismo, realiza una actuación vocal con el protagonista de la película Valiant con Jim Broadbent y John Cleese. También en 2005 se rumoreó que podría ser el nuevo James Bond para la última película de la saga, Casino Royale, antes de anunciarse definitivamente la elección de Daniel Craig. En este mismo año, Ewan actuó junto a Scarlett Johansson en el largometraje La Isla, y en el thriller psicológico Stay (Tránsito) con Naomi Watts.
McGregor ha narrado el show Jet Set de la STV (Televisión Escocesa), acerca de la vida de los cadetes de vuelo (entre ellos su hermano Colin) en la base aérea británica RAF Lossiemouth, en un curso para pilotar los Panavia Tornado, aviones de ataque de la Real Fuerza Aérea británica. Su hermano Colin ha conseguido llegar a ser piloto de la RAF.
En el teatro, ha protagonizado Guys and Dolls en el Piccadilly Theatre de Londres, en el papel de Sky Masterson (el mismo personaje que interpretó Marlon Brando en la gran pantalla). Dicha actuación le valió el reconocimiento de la crítica y el premio al mejor actor 2005 de LastMinute.com. Fue nominado a los premios Olivier por mejor actor de un musical.
Recientemente apareció en el film Cassandra's Dream de Woody Allen, junto al irlandés Colin Farrell, y protagonizará junto a Daniel Craig la adaptación cinematográfica de la novela de Glen Duncan, Lucifer. También se rumorea que actuará en el papel de Kurt Cobain, líder del grupo musical Nirvana en un largometraje sobre dicho grupo. Uno de sus últimos papeles hasta el momento es el del camarlengo Patrick McKenna en la película basada en el libro Ángeles y demonios escrito por Dan Brown. Anteriormente, estrenó el thriller erótico Deception (La lista), coprotagonizado por Hugh Jackman y Michelle Williams. La parte final de esta película se rodó en Madrid.
Aficionado a las motocicletas desde su juventud, McGregor realizó un maratón motociclista junto a su amigo Charley Boorman y el cámara Claudio Von Planta en 2004. Desde mediados de abril hasta finales de julio, viajaron desde Londres hasta Nueva York a través de Europa Central, Ucrania, Rusia, Kazajistán, Mongolia, Siberia y Canadá sobre una moto BMW R1150GS Adventure todo-terreno, acumulando un recorrido de 30.395 km. El viaje, cuya inspiración, ha manisfestado el propio Ewan, le vino del libro Los Viajes de Júpiter de Ted Simon, quedó reflejado también en su libro éxito de ventas Long Way Round y en una serie de televisión con el mismo título (emitida en España por Localia TV, Canal Viajar y Energy).
Durante la aventura, el equipo de rodaje tuvo oportunidad de captar el trabajo que UNICEF realiza en Ucrania, Kazajistán y Mongolia.
Ewan ha hecho un segundo viaje en moto, otra vez junto a su amigo el también actor Charley Boorman, de gran recorrido desde John O'Groats al norte de Escocia hasta Ciudad del Cabo en Sudáfrica, en 2007, llamado Long Way Down, título traducido al castellano como 'Travesía con Ewan McGregor', haciendo referencia al recorrido a través de África. Igualmente el itinerario pasó por centros de trabajo de UNICEF, dado que desde 2004 Ewan McGregor es embajador de buena voluntad de la ONU y ya ha visitado anteriormente varios proyectos de UNICEF, por ejemplo centros para el tratamiento del sida. También tiene pensado un tercer viaje a bordo de su moto, nuevamente con Charley Boorman. Esta vez partirían desde el Cono Sur de Sudamérica hasta llegar a algún punto en el extremo norte de Norteamérica. Siguiendo los nombres de las dos anteriores ediciones, dicho proyecto se llamaría
Long Way Up.
","Ewan_McGregor.jpg");



INSERT INTO ACTORES (NOMBRE_APE,NACIONALIDAD,FECHA_NAC,DESCRIPCION,CARRERA,IMAGEN) VALUES ("Jeremy Renner","EEUU","1971-01-07","Jeremy Lee Renner (nacido el 7 de enero del 1971 en Modesto) es un actor estadounidense.",
"Jeremy Lee Renner (nacido el 7 de enero del 1971 en Modesto) es un actor estadounidense. Renner nació en Modesto, California, siendo el mayor de seis hermanos; Brianna Renner, Nicky Emens, Kim Renner, Clayton Renner y Theo Renner . Sus padres son Lee Renner y Valerie Cearley,y actualmente vive en Los Angeles,CA. Antes de interesarse por el cine, sus pasiones se centraban en la criminología y la computación, pero el teatro pudo más y se trasladó a San Francisco, donde estuvo en producciones locales. Al tiempo se iría a vivir a Los Angeles, donde su vida transcurría entre múltiples audiciones y actuaciones en pequeños teatros.
Respecto a las relaciones amorosas que ha mantenido se sabe muy poco, Jeremy, al interpretar diversos personajes de carácter insano se ha ganado su consideración de antigalán. Tras ser nominado al Oscar y ascender a categoría de estrella se le ha relacionado con Jessica Simpson y Christina Aguilera. Es un gran amigo de Charlize Theron , Colin Farrell,Scarlett Johansson y Eva Longoria.
Jeremy comenzó su carrera cinematográfica acudiendo a diversos castings para series televisivas y películas producidas directamente para la televisión. Salvo en su debut en la comedia Desmadre sobre ruedas (1995), Jeremy se concentró en realizar papeles dramáticos para cintas de thriller o drama.
A finales de los 90s y principios del 2000, Renner apareció en comerciales de Pizza Hut, Duracell y Bud Light. Fue mas ambicioso en sus castings y probó suerte para interpretar papeles secundarios en series televisivas de gran éxito como C.S.I., Ángel o El tiempo de tu vida.
A pesar de protagonizar el drama Fish in a Barrel y la comedia romántica Monkey Love, la película por la que se dió a conocer y por la que obtuvo numerosas alabanzas y nominaciones fue Dahmer(2002), en la que interpreta al conocido psicópata caníbal Jeffrey Dahmer. Este papel le premitió atender a diversos proyectos y elegir determinados papeles. Así, rechazó aparecer en la película Golpe en Hawai para interpretar al ex-S.W.A.T. Brian Gamble en la comercial S.W.A.T., junto a estrellas como Colin Farrell, Samuel L. Jackson o Michelle Rodríguez.
Renner obtuvo fama de tipo duro y corpulento, por lo que la mayoría de los papeles que recibía eran personajes de carácter fuerte como en Verdades ocultas o El fin de la inocencia. En 2005 tuvo la oportunidad de darse a conocer en el cine culto apareciendo junto a Charlize Theron y Woody Harrelson en la oscarizada En tierra de hombres.
En 2007 interpretó a Doyle, un soldado estadounidense enviado al Reino Unido para combatir hordas de zombis en la comercial película de Juan Carlos Fresnadillo 28 semanas después. El mismo año formó parte del reparto de la banda de Jesse James en la oscarizada El asesinato de Jesse James por el cobarde Robert Ford, junto a Brad Pitt, Casey Affleck o Sam Rockwell. También apareció como invitado especial a un episodio de la cuarta temporada de la exitosa serie televisiva House, en la que interpretaba a una estrella de rock con problemas de drogadicción.
Su consolidación como estrella cinematográfica llegó con el papel, de nuevo de soldado estadounidense, Sargento de Primera Clase William James, en la multipremiada película bélica de Kathryn Bigelow The Hurt Locker. A pesar de ser estrenada en 2008, no fue hasta 2009 cuando comenzó a ser galardonada en diversas academias. Finalmente, fue premiada con siete Oscars. Jeremy fue nominado en la categoría de Mejor Actor, pero a pesar de no obtenerlo, si obtuvo un notable reconocimiento que le valió masivas y positivas críticas, creciendo considerablemente su nombre en el mundo del cine.
En 2009 rodó diez episodios para la prometedora serie policiaca The Unusuals, pero finalmente se convirtió en un fracaso, y se canceló el proyecto. Ben Affleck lo contrató para aprecer en su película The Town (2010), un drama policiaco en el que Renner interpreta a James Coughlin, un ladrón de bancos. Jeremy volvió a ser nominado al Oscar, ésta vez como Mejor Actor de Reparto, pero tampoco lo obtuvo.
Renner comenzó a ser rumor para diversas superproducciones, y a finales de 2011 aparecio en la cuarta entrega de Misión Imposible, Misión: Imposible - Protocolo Fantasma. Aceptó ser Clint Barton (Ojo de Halcón), en la película Los Vengadores para 2012, aunque previamente aparece como cameo en la película Thor. El mismo año, aparecerá en una revisión de Hansel y Gretel y pondrá su voz en una nueva secuela de Ice Age. También tiene firmado un contrato para la nueva entrega de la saga Bourne, pero no será el nuevo Jason Bourne (al rechazar el papel Matt Damon), sino que su papel será doble y llevará los nombres de Aaron Cross/Kenneth Gidson. El personaje es independiente del mítico personaje de la saga, pero sigue sus pasos.
","Jeremy_Renner.jpg");



INSERT INTO ACTORES (NOMBRE_APE,NACIONALIDAD,FECHA_NAC,DESCRIPCION,CARRERA,IMAGEN) VALUES ("Rachel Weisz","Reino Unido","1970-03-07","Rachel Hannah Weisz (n. Londres, Inglaterra, 7 de marzo de 1970) es una actriz y modelo británica, ganadora del Óscar, el Globo de Oro, el SAG.",
"Rachel Hannah Weisz (n. Londres, Inglaterra, 7 de marzo de 1970) es una actriz y modelo británica, ganadora del Óscar, el Globo de Oro, el SAG, el Premio Laurence Olivier, el Independent Spirit Awards y otros premios cinematográficos. Ganó reconocimiento público por su interpretación de Evelyn Evy Carnahan-O’Connell en la serie cinematográfica La momia. En 2001, protagonizó junto a Hugh Grant la película About a Boy, y su actuación en El jardinero fiel (2005) le mereció el Premio Óscar de la Academia.
Weisz nació en Westminster, Inglaterra, y creció en el suburbio de Hampstead Garden. Su madre, Edith Ruth (de soltera Teich), es profesora y luego psicoterapeuta nacida en Viena, Austria. Su padre, George Weisz, es un inventor e ingeniero húngaro. Los padres de Weisz se trasladaron a Inglaterra durante la Segunda Guerra Mundial. El padre de Weisz es judío y su madre se ha catalogado como católica, o judía. Weisz creció en un 'hogar cerebralmente judío' y se refiere a si misma como judía. Weisz tiene una hermana, Minnie Weisz, quien es artista.
Weisz se educó en el North London Collegiate School. Más tarde ingresó a Benenden School y después se matriculó en St Paul's Girls' School. Ingresó a Trinity Hall de la Universidad de Cambridge, donde se graduó de literatura inglesa con una calificación 2:1. Durante sus años universitarios apareció en varias producciones estudiantiles, siendo cofundadora el grupo teatral estudiantil Cambridge Talking Tongues, la cual ganó el Guardian Student Drama Award en el Festival de Edimburgo gracias a una improvisación llamada Slight Possession.
Después de trabajar inicialmente en la televisión, Weisz comenzó su carrera fílmica en 1996 en el filme de Bernardo Bertolucci, Belleza robada. En 2001 regresaría al teatro, en el papel de Evelyn en The Shape of Things.
Se hizo conocida por los filmes La Momia, su secuela El regreso de la momia y Enemigo a las puertas, en los que realizó notables interpretaciones. Su papel en Constantine fue uno de los últimos de tipo comercial antes de su paso a un tipo de cine con mayor trasfondo.
En 2006 Rachel Weisz ganó el Óscar a la mejor actriz de reparto por su papel de Tessa Quayle en la película El jardinero fiel de Fernando Meirelles.
Weisz no pudo realizar la momia 3 Protagonizó la película Ágora (2009) del director español Alejandro Amenábar, interpretando el papel de Hipatia.
Weisz también es como una musa para el diseñador de moda Narciso Rodriguez.
Weisz estuvo comprometida con el productor y director de cine estadounidense Darren Aronofsky, con quien salió desde 2001 hasta noviembre de 2010. Tienen un hijo, Henry Chance, nacido el 31 de mayo de 2006 en Nueva York. La pareja residía en East Village, en Manhattan. El 9 de noviembre del 2010 anunciaron su ruptura matrimonial tras 9 años juntos. Contrajo matrimonio con el actor británico Daniel Craig el 22 de junio de 2011 en una ceremonia secreta en Nueva York, tras varios meses de noviazgo.
","Rachel_Weisz.jpg");



INSERT INTO ACTORES (NOMBRE_APE,NACIONALIDAD,FECHA_NAC,DESCRIPCION,CARRERA,IMAGEN) VALUES ("Thomas Mann","EEUU","1991-09-27","Thomas Mann (nacido el 27 de septiembre 1991) es un actor estadounidense. Él es mejor conocido por su papel de Thomas Kub en Projecto X.",
"Thomas Mann (nacido el 27 de septiembre 1991) es un actor estadounidense. Él es mejor conocido por su papel de Thomas Kub en Projecto X.
Mann nació en Portland, Oregon. Ha vivido en Dallas, Texas, desde que tenía 2 años de edad.
En 2009, Mann hizo su debut como actor en la sitcom de Nickelodeon iCarly. En octubre de 2010, Mann hizo su debut en el cine junto a Emma Roberts y Zach Galifianakis en la película de comedia-drama que es una especie de historia divertida. Ese mismo año, Mann fue elegido como el protagonista de la comedia negra Proyecto X. A Mann se le dijo que no podía audicionar para la película ya que los productores sólo deseaban gente sin créditos actorales; Mann recibió finalmente el papel después de audicionar siete veces. La película se centra en Thomas Kub, que realiza una fiesta por su cumpleaños que, casi desde el principio de la celebración, se le va de las manos. La filmación comenzó en junio de ese mismo año en Los Angeles, California, con un presupuesto de $ 12 millones. La película recibió críticas negativas de los críticos, pero fue un éxito de taquilla y recaudó más de
$ 100 millones a nivel mundial. Una secuela planeada se cree que esta en fase de desarrollo y no se sabe si Mann volverá. En abril de 2011, Mann fue confirmado para protagonizar el Fun Size de Paramount Pictures; Es una comedia adolescente, que es protagonizada por Victoria Justice. La película se centra en el personaje de Justice, cuyo hermano se pierde cuando va a una fiesta. Las inclemencias retrasaron el rodaje hasta inicios del 2012. The OC marco la película como el debut cinematográfico direccional del creador de Gossip Girl, Josh Schwartz y fue lanzada en octubre de 2012. En marzo de 2012, la revista de entretenimiento Variety dijo que Mann protagonizará la adaptación cinematográfica de la novela de 2006, King Dork. Seth Gordon se establece para dirigir la película.
","Thomas_Mann.jpg");



INSERT INTO ACTORES (NOMBRE_APE,NACIONALIDAD,FECHA_NAC,DESCRIPCION,CARRERA,IMAGEN) VALUES ("Oliver Cooper","EEUU","1990-04-20","El actor Oliver Cooper nació en Sylvania, un suburbio de la ciudad de Toledo, Ohio, en los Estados Unidos.",
"El actor Oliver Cooper nació en Sylvania, un suburbio de la ciudad de Toledo, Ohio, en los Estados Unidos. Cooper se graduó en la Sylvania Northview High School en el año 2008; durante esa época ya interpretaba monólogos en clubes locales. Tras estudiar un año en la Arizona State University, decidió mudarse a la ciudad de Los Ángeles cuando contaba con sólo 19 años de edad. En su, hasta el momento corta carrera, Oliver debutó frente a cámaras, en el cortometraje 'Weekend Dad', en el año 2010. Un año más tarde, protagonizó, y también produjo el corto 'Rick White', dirigido por su amigo de Sylvania, Joe Burke. Burke también fue el director del corto 'Marriage Drama with Virginia Madsen' (2011), basado en una historia que escribió Cooper y que también protagonizó junto a la actriz Virginia Madsen.
En 2012 se estrenó 'Proyecto X' que marcó su debut en un largometraje; en él, Cooper coprotagoniza con Thomas Mann y Jonathan Daniel Brown una típica historia de estudiantes secundarios que, tratando de ser populares, organizan una fiesta que se sale de control. La película, que contó con un presupuesto de 21 millones de dólares, recaudó más del doble en las dos primeras semanas de estreno, lanzando la carrera de Oliver quien se encuentra actualmente involucrado en varios otros proyectos cinematográficos.
","Oliver_Cooper.jpg");



INSERT INTO ACTORES (NOMBRE_APE,NACIONALIDAD,FECHA_NAC,DESCRIPCION,CARRERA,IMAGEN) VALUES ("Johnny Depp","EEUU","1963-06-09","John Christopher Depp II (Owensboro, Kentucky; 9 de junio de 1963), conocido artísticamente como Johnny Depp, es un actor y productor estadounidense nominado en tres oportunidades al Óscar.",
"John Christopher Depp II (Owensboro, Kentucky; 9 de junio de 1963), conocido artísticamente como Johnny Depp, es un actor y productor estadounidense nominado en tres oportunidades al Óscar y ganador de un Globo de Oro, un Premio del Sindicato de Actores y de un Premio César.
Johnny Depp nació en Owensboro, Kentucky, hijo de la camarera Betty Sue Palmer —cuyo apellido de soltera era Wells— y John Christopher Depp, Sr., un ingeniero civil. Tiene un hermano, Daniel (que es escritor), y dos hermanas: Christie, que trabaja como su administradora personal, y Debbie. Cabe señalar que Depp tiene ascendencias francesa, alemana, cheroqui e irlandesa, por lo que el propio Depp se autocalifica en entrevistas como un perro mestizo. Según algunos biógrafos, la familia estadounidense Depp surgió cuando un inmigrante francés hugonote, Pierre Deppe o Dieppe, se estableció en Virginia aproximadamente en 1700, y se integró en una colonia de refugiados ubicada sobre la cascada del río James.
Depp se mudó varias veces en su infancia: más de veinte lugares de mudanza acabaron en Miramar (Florida) cuando el actor tenía tan solo siete años. En 1978, con 15 años de edad, sus padres se divorciaron y tuvo una etapa bohemia, durante la cual se sumió en las drogas. Depp, que dice estar limpio, considera esta etapa como superada.
Johnny Depp se hizo copropietario del famoso bar The Viper Room, y dejó de serlo en 2004, conocido por la muerte de la celebridad River Phoenix, quien murió frente a éste en 1993 y por lo cual Johnny Depp cerraba el bar cada 31 de octubre en honor al actor. Los críticos atacaron diciendo que ese lugar era la 'cuna de la marihuana de Los Ángeles'. Perturbado por la muerte y por cómo los paparazzi jugaban con el tema, Depp terminó cerrándolo durante una semana.
Una de las peores etapas por las que pasó fue como dice: la etapa oscura de mi vida: durante su separación con Ryder, Johnny asistía a ciertas fiestas liberales como una forma de olvidarse por todo el dolor que había pasado. Después, Depp fue detenido por romper una suite de Nueva York. Según explicó: 'Llegué a mi cuarto muy cansado, abrí el armario, y de repente un armadillo saltó hacia los muebles, destruyendo todo a su paso y al terminar saltó a la ventana y se fue dejando todo el desastre'.
En 1983, tres años después de su llegada a California, Depp se casó con la maquilladora Lori Anne Allison, de quien se terminó divorciando en 1985. Salió con las actrices Sherilyn Fenn, Jennifer Grey y Winona Ryder, y con la modelo Kate Moss. En 1998 comenzó su relación con la actriz y cantante francesa Vanessa Paradis; ella captó su atención en la sala de un hotel en París mientras él filmaba la película The Ninth Gate (1999) en el mismo lugar. Contrariamente a la opinión popular, la pareja no se casó, aunque tuvieron una hija, Lily-Rose Melody Depp (27/05/1999) y un hijo, John (Jack) Christopher Depp III (09/04/2002). La pareja dividía su tiempo entre Hollywood y una campiña al sur de Francia, y también tenían apartamentos en París y Manhattan. Además, Depp compró una isla en las Bahamas. En junio de 2012, tras varios meses de rumores al respecto, Johnny Depp y Vanessa Paradis confirmaron su separación.
Johnny es un ávido lector y en su tiempo libre disfruta de la pintura. Ha dibujado la portada del CD de Vanessa Paradis Divinidylle que aparece en el inicio del video L'incendie. También ha pintado al actor Marlon Brando y a Keith Richards, guitarrista de los Rolling Stones. Además, colecciona obras de arte y visita museos de arte.
Antes de ser actor, trabajaba como vendedor cobrando $25 semanales. Entonces conoció a Nicolas Cage y éste le animó a probar suerte en el mundo de la interpretación. Su primer papel fue en A Nightmare on Elm Street (1984), dirigida por Wes Craven. Sin embargo, la fama le llegó al interpretar al policía Tommy Hanson en 21 Jump Street (1987-1991).
Entre sus papeles, destacan los de Edward Scissorhands (1990), Ed Wood (1994), Don Juan DeMarco (1995), Donnie Brasco (1997), Fear and Loathing in Las Vegas (1998), The Ninth Gate (1999), Antes que anochezca (2001), Finding Neverland (2004), Pirates of the Caribbean: the curse of the Black Pearl (2003), Pirates of the Caribbean: Dead Man's Chest (2006), Piratas del Caribe: en el fin del mundo (2007) y Pirates of the Caribbean: On Stranger Tides (2011).
Entre los proyectos que rechazó destacan Leyendas de pasión, Speed, Entrevista con el vampiro o Sin City. Por otra parte, fue considerado para películas como Titanic, Batman Forever, la trilogía Matrix y Hulk.
Parte de sus colaboraciones más reconocidas son las que forma con el director Tim Burton. Ha participado en ocho de sus películas: Edward Scissorhands, Ed Wood, Sleepy Hollow (1999), Charlie Y La Fábrica De Chocolate (2005), Corpse Bride (2005), Sweeney Todd (2007), Alicia En El País De Las Maravillas (2010) y Sombras Tenebrosas (2012).
Depp siempre se ha interesado por personajes peculiares, marginados o simplemente diferentes, como Edward Scissorhands o Willy Wonka.
El 18 de febrero de 2008, el portavoz del actor Jude Law informó que éste junto con Depp y Colin Farrell sustituirían en las escenas finales al fallecido actor Heath Ledger en la película The Imaginarium of Doctor Parnassus,. Por otro lado, ha protagonizado junto a Penélope Cruz la cuarta entrega de Piratas del Caribe, Pirates of the Caribbean: On Stranger Tides, que se estrenó el 20 de mayo de 2011.
Johnny interpretó al vampiro Barnabas Collins en Sombras Tenebrosas, la adaptación cinematográfica de una antigua serie de televisión. La película, estrenada en 2012, fue dirigida por Tim Burton. Robert Rodríguez declaró que pretendía contar con Johnny Depp para la secuela de Sin City y retomar el papel del agente de la CIA Sheldon Sands, que interpretó en Once upon a time in Mexico en una nueva película centrada en este personaje. La productora Infinitum Nihil, de la que Johnny Depp es copropietario, ha adquirido los derechos para la adaptación cinematográfica de la novela El manuscrito de Dante, que él protagonizará, según ha informado la revista Variety.
Vanity Fair publicó la lista de los Top 40 celebridades de Hollywood con más ingresos a lo largo de 2010 y Depp fue clasificado el número 2 en la lista, con ingresos estimados en $100 millones por sus películas. Depp ha colaborado con el director y amigo Tim Burton en ocho películas.
","Johnny_Depp.jpg");




INSERT INTO ACTORES (NOMBRE_APE,NACIONALIDAD,FECHA_NAC,DESCRIPCION,CARRERA,IMAGEN) VALUES ("Michelle Pfeiffer","EEUU","1958-04-29","Michelle Marie Pfeiffer (Santa Ana, California; 29 de abril de 1958) es una actriz estadounidense.",
"Michelle Marie Pfeiffer (Santa Ana, California; 29 de abril de 1958) es una actriz estadounidense. Además de su trabajo actoral, por el que ha sido nominada en tres ocasiones a los premios Óscar y en seis a los premios Globo de Oro, su significativa presencia mediática se debe también a su consideración como una de las mujeres más atractivas del mundo. Pfeiffer comenzó su carrera actoral al aparecer como invitada en programas de televisión, entre los que se incluyen papeles pequeños en las series La isla de la fantasía y Delta House, a finales de los años 1970. Debutó en el cine en 1980 en el largometraje The Hollywood Knights. Posteriormente, obtuvo reconocimiento de la prensa y los críticos con la interpretación de papeles en películas como Las Amistades Peligrosas (1988), Casada con todos (1988), Los fabulosos Baker Boys (1989), La casa Rusia (1990), Frankie & Johnny (1991), Por encima de todo (1992),
Batman vuelve (1992) y La edad de la inocencia (1993). Sus interpretaciones la hicieron acreedora de numerosos premios y galardones, entre ellos un premio BAFTA, un Globo de Oro y un Oso de Plata.
Michelle nació en Santa Ana (condado de Orange, California) y tiene tres hermanos, Richard, mayor que Michelle, Dedee (actriz) y Lori (Modelo) menores que ella. Es de ascendencia neerlandesa, alemana, irlandesa, sueca y suiza. Su primer salario lo ganó sacando brillo a las máquinas de aire acondicionado que su padre arreglaba. En la escuela siempre se comportó como un chico, según propias palabras de la actriz, y no llamaba la atención de los muchachos. Años más tarde, fue la típica chica rubia que se saltaba las clases para pasar las tardes con sus amigos surfistas, tomando batidos y alguna que otra droga en la playa. En 1981 se casó con el también actor Peter Horton, del que se divorció en 1988. Después tuvo idilios con Michael Keaton, John Malkovich y Fisher Stevens, con el que planeó una boda, pero una infidelidad del actor dejó de nuevo a Michelle soltera. En 1993 adoptó a Claudia Rose, una niña, hija
de una enfermera que ya tenía cuatro hijos y que no podía ocuparse de uno más y se casó con el productor David E. Kelley, creador de Chicago Hope o Ally McBeal, con el que tuvo a John Henry (1994). Su primera experiencia con el mundo del espectáculo fue interpretando a Alicia, en la cabalgata de Disneyland de Alicia en el País de las Maravillas en 1970 con tan solo 12 años.
Años más tarde y apoyada por su peluquero, se presenta al concurso de belleza 'Miss Orange County' el cual gana. En el jurado del certamen había un cazatalentos que la contrata para intentar promocionarla, primero como modelo, rodando spots publicitarios, para más tarde colaborar como actriz en series de televisión como 'Delta House', 'La Isla de la Fantasía', 'Chips' hasta conseguir ser la chica guapa en su propia serie 'B.A.D. Cats', serie que duró solamente una temporada por su bajo nivel de audiencia. Por aquella época, entre 1978 y 1981, participa también en varios telefilms, siempre como actriz secundaria. En 1980 debuta para la gran pantalla en la cinta 'Volver al amor', junto a Elliot Gould y Susannah York, en el rol de S. York cuando era adolescente. Le siguen varios trabajos en películas de escasa relevancia como 'La maldición de la reina dragón' y 'The Hollywood Knights', siempre como actriz secundaria.
En 1982 le llegó la oportunidad de interpretar un papel protagonista en el musical Grease 2, como Stephanie Zinone. La película fue un fracaso de crítica y público, lo único apreciable de esta secuela fue Michelle, a la que nominaron a un premio como mejor actriz debutante. Debido al fracaso de esta cinta, la actriz estuvo más de un año sin trabajar.
Tras varios años de interpretar roles de reparto y frecuentes apariciones en televisión como invitada, Pfeiffer obtuvo amplio reconocimiento por su actuación en la película de 1983 El precio del poder. Encarnó a Elvira Hancock, una mujer adicta a la cocaína, esposa de Tony Montana (Al Pacino); allí trabajó bajo la dirección de Brian De Palma.
Después de intervenir en esta película todos los papeles que le ofrecían eran de mujer fría y calculadora, pero ella optó por uno totalmente opuesto, la doncella encantada por un maleficio en la película de aventuras Lady Halcón de Richard Donner junto a Matthew Broderick y Rutger Hauer. Tras el éxito de esta y su anterior película, a la joven actriz ya le llovían las ofertas, ya era una actriz a la que la gente reconocía pero de la que todavía no se habían aprendido el nombre. En 1985 fue la protagonista femenina de Cuando llega la noche de John Landis. Comedia que protagonizó junto al emergente actor Jeff Goldblum. Un año después es dirigida por Alan Alda en la comedia 'Dulce Libertad' compartiendo cartel con Michael Caine y Bob Hoskins.
Vuelve a la televisión para protagonizar algunos telefilms y ya en 1987 se convierte en una de las tres brujas que atormentan al demonio en la comedia fantástica Las brujas de Eastwick junto a Jack Nicholson, Cher y Susan Sarandon. El enorme éxito de la película hizo que Michelle fuese una de las actrices más solicitadas de la época. Ya era toda una estrella.
En 1988 logró su primera nominación de seis consecutivas a los Globo de Oro por Casada con todos de Jonathan Demme, una disparatada comedia sobre la mafia que la emparejó con Matthew Modine y Alec Baldwin. La película fue un éxito moderado pero sirvió para que grandes directores apreciaran que tras ese extraordinario físico se escondía una actriz de talento. Su siguiente film, todavía en 1988, fue el thriller Conexión Tequila junto a Mel Gibson y Kurt Russell. Pero es Las relaciones peligrosas de Stephen Frears la película que realmente la sitúa entre las mejores actrices de la década, ganando varios premios por su interpretación y siendo nominada por primera vez a los Premio Oscar como mejor actriz secundaria. En esta cinta la acompañaban Glenn Close y John Malkovich, formando el trío protagonista, y Uma Thurman y Keanu Reeves dos actores casi debutantes, como parte del magnífico reparto. 1989 sería el año en el
que Michelle ganó todos los premios que se otorgaron a la mejor actriz excepto el Premio Oscar por su participación en Los fabulosos Baker Boys del debutante Steve Kloves, donde daba vida a una cantante de salón acompañada por los pianos de los hermanos Baker, interpretados por Jeff Bridges y Beau Bridges hermanos en la vida real. Gracias a esta película y a la escena en la que canta vestida de rojo encima de un piano, es considerada como uno de los mayores sex-symbols de la historia del cine.
","Michelle_Pfeiffer.jpg");




INSERT INTO ACTORES (NOMBRE_APE,NACIONALIDAD,FECHA_NAC,DESCRIPCION,CARRERA,IMAGEN) VALUES ("Jason Biggs","EEUU","1978-05-12","Jason Matthew Biggs (Hasbrouck Heights, Nueva Jersey, Estados Unidos 12 de mayo de 1978) es un actor ítalo-estadounidense que alcanzó la fama con su papel de Jim Levenstein en la saga cómica American Pie.",
"Jason Matthew Biggs (Hasbrouck Heights, Nueva Jersey, Estados Unidos 12 de mayo de 1978) es un actor ítalo-estadounidense que alcanzó la fama con su papel de Jim Levenstein en la saga cómica American Pie.
Biggs nació en Pompton Plains, Nueva Jersey, hijo de Angela, una enfermera, y Gary Biggs, un gerente de una compañía de envío. Creció en Hasbrouck Heights, Nueva Jersey, y asistió al Hasbrouck Heights High School. Biggs tuvo éxito en los deportes mientras estaba en la secundaria, en tenis y lucha libre. Ganó un título estatal en su último año y avanzó a las rondas finales en un torneo nacional.
Biggs es italo-americano y católico romano; él ha mencionado en entrevistas que es a menudo elegido como un personaje judío, como lo fue en American Pie (otros ejemplos incluyen en Saving Silverman y Anything Else), aunque no es judío.
En enero de 2008, se comprometió con la actriz Jenny Mollen; y se casaron el 23 de abril de 2008. Actualmente vive en Los Ángeles, California. Biggs comenzó a actuar a los cinco años. En 1992, hizo su debut en televisión en la serie Drexell's Class. También hizo un especial de HBO, The Fotis Sevastakis Story, debido a los argumentos de concesión de licencias, nunca salió al aire. Ese mismo año, Biggs debutó en Broadway, en Conversations with My Father, que lo ayudó a participar en As the World Turns. Estuvo nominado por un premio al Mejor Actor Joven en una telenovela en los Premios Emmy por este papel.
Biggs asistió a la Universidad de Nueva York desde 1996 a 1997, pero poco después, regresó a seguir su carrera de actuación. Actuó en otra serie, Camp Stories en 1997. Luego protagonizó en American Pie, que fue un éxito internacional y tuvo cuatro secuelas (con Biggs), siendo la última entrega en el 2012 y seis spin offs (que no son protagonizadas por Biggs). Biggs ha aceptado papeles en películas como Loser en 2000, y otras. En 2004 y 2005, Biggs interpretó a un judío ortodoxo en Modern Orthodox, en Nueva York. En 2006, fue visto en el realy show de MTV Blowin' Up, con Jamie Kennedy y Stu Stone.
Biggs aparece en la película Jay and Silent Bob Strike Back, con James Van Der Beek como Jay. Ha aparecido en otras películas, como Texas Rangers, Scary Movie y Over Her Dead Body. Biggs retomó su papel como Jim Levenstein en American Reunion, lanzada el 6 de abril de 2012.
","Jason_Biggs.jpg");




INSERT INTO ACTORES (NOMBRE_APE,NACIONALIDAD,FECHA_NAC,DESCRIPCION,CARRERA,IMAGEN) VALUES ("Seann William Scott","EEUU","1976-10-03","Sean William Scott (nació el 3 de octubre de 1976, Cottage Grove, Minnesota, Estados Unidos) es un modelo, actor y comediante conocido por su papel de Steve Stifler en American Pie.",
"Sean William Scott (nació el 3 de octubre de 1976, Cottage Grove, Minnesota, Estados Unidos) es un modelo, actor y comediante conocido por su papel de Steve Stifler en American Pie, una serie de comedias adolescentes. También es conocido por su papel en The Rundown, Destino Final, Road Trip, Evolución, Dude, Where's My Car?, Los Dukes de Hazzard y Role Models.
Scott es el más joven de siete hermanos. Nació en Cottage Grove, Minnesota, hijo de Patricia Ann, un ama de casa y William Frank Scott, obrero. Mientras estaba en la Universidad de Wisconsin-Madison, el mayor de sus hermanos, Daniel, le ayudó a fundar The Onion, en donde fue uno de los primeros escritores. Decidió ser actor cuando trabajaba en una sala de cine local. Veía todas las películas que podía en su tiempo libre. Se graduó de la Escuela Primaria Crestview y Park High School. Después de su graduación, asistió a Glendale Community College. Su primera actuación profesional fue en televisión, en el vídeo musical de Hole in My Soul de Aerosmith. Poco después del vídeo, apareció en el programa Chad's World, un programa de televisión de temática gay difundido en la web por la efímera Digital Entertainment Network.
Comenzó su carrera como actor en los teatros de Broadway, actuando en varias comedias musicales. El primer éxito comercial de Scott llegó en 1999 con la película American Pie como Steve Stifler, un papel que interpretó en tres secuelas American Pie 2, American Wedding y American Reunion Durante una entrevista para la BBC Radio 1 contó que sólo cobró 8.000 dólares por esa primera película. Aunque el personaje de Steve Stifler ha marcado un hito, el actor ha mencionado en diversas entrevistas que su temor a encasillarse le ha llevado a elegir interpretar diferentes tipos de personajes. Después de American Pie, hizo de estudiante en la película Destino final y un personaje inofensivo como Chester en Colega, ¿Dónde está mi coche? en España y Hey, ¿dónde está mi auto? en Hispanoamérica junto a su mejor amigo de la vida real, Ashton Kutcher.
Hizo una aparición en Jay y Bob el Silencioso contraatacan como guitarrista y activista de los derechos de los animales. Como un agente de policía ha protagonizado Southland Tales, donde se reencuentra con el actor Dwayne Johnson. Scott fue copresentador de los MTV Movie Awards 2003, junto con Justin Timberlake. Los dos hicieron parodiaron varias escenas de The Matrix Reloaded, con un éxito tan grande que incluso esas parodias se recogen en el DVD de la película. También ha participado en Saturday Night Live y apareció como co-anfitrión invitado en En vivo con Regis y Kelly.
En 2010 participó en una comedia de acción junto a Bruce Willis, Tracy Morgan, Jim Norton y Adam Brody llamada Cop Out. Y el año pasado participó en Jackass 3D.
","Seann_William_Scott.jpg");




INSERT INTO ACTORES (NOMBRE_APE,NACIONALIDAD,FECHA_NAC,DESCRIPCION,CARRERA,IMAGEN) VALUES ("Alyson Hannigan","EEUU","1974-03-24","Alyson Lee Hannigan-Denisof (24 de marzo de 1974, Washington D.C., Estados Unidos), más conocida como Alyson Hannigan, es una actriz conocida por sus papeles de Willow Rosenberg en Buffy, la cazavampiros.",
"Alyson Lee Hannigan-Denisof (24 de marzo de 1974, Washington D.C., Estados Unidos), más conocida como Alyson Hannigan, es una actriz conocida por sus papeles de Willow Rosenberg en Buffy, la cazavampiros, Michelle Flaherty en todas las películas de la saga American Pie, y Lily Aldrin en How I Met Your Mother.
Hannigan, unica hija de la corredora de bienes raíces Emilie Posner y el camionero Al Hannigan, es judía por parte de madre y también tiene ascendencia irlandesa.  Un año después de su nacimiento, sus padres se separaron y ella se crio principalmente en Atlanta junto a su madre. Asistió a la Escuela Preparatoria North Hollywood, donde audicionó con éxito para los agentes, mientras visitaba a su padre en Santa Bárbara. Estudió en la Universidad Estatal de California, Northridge.
A pesar de haber aparecido en un film industrial para Active Parenting y en un anuncio para las galletas Duncan Hines (1978), no comenzó oficialmente su carrera hasta 1985. Debutó en el cine ese mismo año con Impure Thoughts. Su primer gran papel fue en la película cómica de ciencia ficción Mi novia es un extraterrestre (1988). Como curiosidad cabe decir que uno de sus compañeros fue Seth Green, que sería su novio en la ficción en Buffy, la cazavampiros.
En 1989 consiguió su primer papel regular en Free Spirit (ABC). A lo largo de los 90 apareció en varios anuncios de televisión. Durante esa década también protagonizó varios telefilmes como Cambiadas al nacer (1991) o A case for life (1996).
En 1997 consiguió el papel de Willow Rosenberg en Buffy, la cazavampiros, serie que se convirtió en un éxito y que le sirvió el reconocimiento del público. En su recta final en la serie (2003), la actriz cobraba 250.000 dólares por episodio. Gracias a su trabajo en esta serie, Hannigan apareció en American Pie, American Pie 2, American Wedding y Boys and Girls. Recuperó su papel de Willow en la séptima temporada de la serie y en la cuarta del spin-off de ésta: Angel.
A principios de 2004 realizó su debut en el West End de Londres protagonizando una adaptación teatral de When Harry Met Sally..., en el Teatro Haymarket, junto a Luke Perry.
Fue en 2005 cuando inició su etapa en la serie How I Met Your Mother como Lily Aldrin. Además, en ese mismo año, interpretó a Trina Echolls en Veronica Mars. Un año más tarde apareció en Date Movie como Julia Jones.
Alyson unió fuerzas con Emily Deschanel, Jaime King, Minka Kelly y Katharine McPhee para promover la campaña de screening del cáncer de mama de la organización Stand Up 2 Cancer, mediante un vídeo de una pijamada publicado en el sitio web de Funny or Die.
Mantuvo una relación sentimental con Ginger Fish, de la banda Marilyn Manson.  Se casó con el actor Alexis Denisof el 11 de octubre de 2003 en el Two Brunch Palms Resort, en Desert Hot Springs. Ambos adquirieron una casa en Santa Mónica y el 24 de marzo de 2009, cumpleaños de Alyson, nació su primera hija: Satyana Denisof. A finales del 2011 (después de muchas especulaciones) la actriz confirmó en Twitter que está embarazada por segunda ocasión, coincidiendo con el embarazo de su personaje Lily Aldrin en How I Met Your Mother. Su segunda hija, Keeva Jane, nació el 23 de mayo de 2012.
","Alyson_Hannigan.jpg");