#plantilla insert actua
#INSERT INTO ACTUA(ID_ACTOR, ID_PELICULA) VALUES ('', '');


INSERT INTO ACTUA(ID_ACTOR, ID_PELICULA) VALUES ('1', '1');
INSERT INTO ACTUA(ID_ACTOR, ID_PELICULA) VALUES ('2', '1');
INSERT INTO ACTUA(ID_ACTOR, ID_PELICULA) VALUES ('3', '1');


INSERT INTO ACTUA(ID_ACTOR, ID_PELICULA) VALUES ('4', '2');
INSERT INTO ACTUA(ID_ACTOR, ID_PELICULA) VALUES ('5', '2');
INSERT INTO ACTUA(ID_ACTOR, ID_PELICULA) VALUES ('6', '2');


INSERT INTO ACTUA(ID_ACTOR, ID_PELICULA) VALUES ('7', '3');
INSERT INTO ACTUA(ID_ACTOR, ID_PELICULA) VALUES ('8', '3');
INSERT INTO ACTUA(ID_ACTOR, ID_PELICULA) VALUES ('9', '3');


INSERT INTO ACTUA(ID_ACTOR, ID_PELICULA) VALUES ('10', '4');
INSERT INTO ACTUA(ID_ACTOR, ID_PELICULA) VALUES ('11', '4');


INSERT INTO ACTUA(ID_ACTOR, ID_PELICULA) VALUES ('12', '5');
INSERT INTO ACTUA(ID_ACTOR, ID_PELICULA) VALUES ('13', '5');


INSERT INTO ACTUA(ID_ACTOR, ID_PELICULA) VALUES ('14', '6');


INSERT INTO ACTUA(ID_ACTOR, ID_PELICULA) VALUES ('15', '7');
INSERT INTO ACTUA(ID_ACTOR, ID_PELICULA) VALUES ('16', '7');


INSERT INTO ACTUA(ID_ACTOR, ID_PELICULA) VALUES ('17', '8');
INSERT INTO ACTUA(ID_ACTOR, ID_PELICULA) VALUES ('18', '8');


INSERT INTO ACTUA(ID_ACTOR, ID_PELICULA) VALUES ('19', '9');
INSERT INTO ACTUA(ID_ACTOR, ID_PELICULA) VALUES ('20', '9');


INSERT INTO ACTUA(ID_ACTOR, ID_PELICULA) VALUES ('21', '10');
INSERT INTO ACTUA(ID_ACTOR, ID_PELICULA) VALUES ('22', '10');


INSERT INTO ACTUA(ID_ACTOR, ID_PELICULA) VALUES ('23', '11');
INSERT INTO ACTUA(ID_ACTOR, ID_PELICULA) VALUES ('24', '11');


INSERT INTO ACTUA(ID_ACTOR, ID_PELICULA) VALUES ('25', '12');
INSERT INTO ACTUA(ID_ACTOR, ID_PELICULA) VALUES ('26', '12');
INSERT INTO ACTUA(ID_ACTOR, ID_PELICULA) VALUES ('27', '12');