#plantilla insert gen_pel
#INSERT INTO GEN_PEL(ID_GENERO, ID_PELICULA) VALUES ('', '');


INSERT INTO GEN_PEL(ID_GENERO, ID_PELICULA) VALUES ('2', '1');
INSERT INTO GEN_PEL(ID_GENERO, ID_PELICULA) VALUES ('1', '1');
INSERT INTO GEN_PEL(ID_GENERO, ID_PELICULA) VALUES ('6', '1');

INSERT INTO GEN_PEL(ID_GENERO, ID_PELICULA) VALUES ('1', '2');

INSERT INTO GEN_PEL(ID_GENERO, ID_PELICULA) VALUES ('4', '3');
INSERT INTO GEN_PEL(ID_GENERO, ID_PELICULA) VALUES ('3', '3');
INSERT INTO GEN_PEL(ID_GENERO, ID_PELICULA) VALUES ('9', '3');
INSERT INTO GEN_PEL(ID_GENERO, ID_PELICULA) VALUES ('1', '3');
INSERT INTO GEN_PEL(ID_GENERO, ID_PELICULA) VALUES ('7', '3');
INSERT INTO GEN_PEL(ID_GENERO, ID_PELICULA) VALUES ('8', '3');

INSERT INTO GEN_PEL(ID_GENERO, ID_PELICULA) VALUES ('2', '4');
INSERT INTO GEN_PEL(ID_GENERO, ID_PELICULA) VALUES ('6', '4');
INSERT INTO GEN_PEL(ID_GENERO, ID_PELICULA) VALUES ('10', '4');

INSERT INTO GEN_PEL(ID_GENERO, ID_PELICULA) VALUES ('7', '5');
INSERT INTO GEN_PEL(ID_GENERO, ID_PELICULA) VALUES ('3', '5');
INSERT INTO GEN_PEL(ID_GENERO, ID_PELICULA) VALUES ('1', '5');

INSERT INTO GEN_PEL(ID_GENERO, ID_PELICULA) VALUES ('3', '6');
INSERT INTO GEN_PEL(ID_GENERO, ID_PELICULA) VALUES ('6', '6');

INSERT INTO GEN_PEL(ID_GENERO, ID_PELICULA) VALUES ('1', '7');
INSERT INTO GEN_PEL(ID_GENERO, ID_PELICULA) VALUES ('2', '7');

INSERT INTO GEN_PEL(ID_GENERO, ID_PELICULA) VALUES ('6', '8');

INSERT INTO GEN_PEL(ID_GENERO, ID_PELICULA) VALUES ('1', '9');

INSERT INTO GEN_PEL(ID_GENERO, ID_PELICULA) VALUES ('11', '10');

INSERT INTO GEN_PEL(ID_GENERO, ID_PELICULA) VALUES ('11', '11');
INSERT INTO GEN_PEL(ID_GENERO, ID_PELICULA) VALUES ('5', '11');
INSERT INTO GEN_PEL(ID_GENERO, ID_PELICULA) VALUES ('7', '11');

INSERT INTO GEN_PEL(ID_GENERO, ID_PELICULA) VALUES ('11', '12');