#plantilla insert generos
#INSERT INTO GENEROS(NOM_GENERO) VALUES ('');


INSERT INTO GENEROS(NOM_GENERO) VALUES ('Acción');
INSERT INTO GENEROS(NOM_GENERO) VALUES ('Thriller');
INSERT INTO GENEROS(NOM_GENERO) VALUES ('Aventuras');
INSERT INTO GENEROS(NOM_GENERO) VALUES ('Ciencia ficción');
INSERT INTO GENEROS(NOM_GENERO) VALUES ('Terror');
INSERT INTO GENEROS(NOM_GENERO) VALUES ('Drama');
INSERT INTO GENEROS(NOM_GENERO) VALUES ('Fantastico');
INSERT INTO GENEROS(NOM_GENERO) VALUES ('Romance');
INSERT INTO GENEROS(NOM_GENERO) VALUES ('Bélico');
INSERT INTO GENEROS(NOM_GENERO) VALUES ('Intriga');
INSERT INTO GENEROS(NOM_GENERO) VALUES ('Comedia');